name: neuralxc
channels:
  - conda-forge
  - defaults
dependencies:
  - _tflow_select=2.3.0=mkl
  - absl-py=0.7.0=py36_0
  - ase=3.17.0=py_1
  - astor=0.7.1=py36_0
  - atomicwrites=1.3.0=py36_1
  - attrs=19.1.0=py36_1
  - backcall=0.1.0=py36_0
  - blas=1.0=mkl
  - bleach=3.1.0=py36_0
  - bokeh=1.0.4=py36_0
  - c-ares=1.15.0=h7b6447c_1
  - ca-certificates=2019.3.9=hecc5488_0
  - certifi=2019.3.9=py36_0
  - click=7.0=py_0
  - cloudpickle=0.8.0=py36_0
  - cycler=0.10.0=py36_0
  - cytoolz=0.9.0.1=py36h14c3975_1
  - dask=1.1.4=py36_1
  - dask-core=1.1.4=py36_1
  - dask-glm=0.1.0=0
  - dask-ml=0.12.0=py_0
  - dbus=1.13.6=h746ee38_0
  - decorator=4.4.0=py36_1
  - defusedxml=0.5.0=py36_1
  - distributed=1.26.0=py36_1
  - entrypoints=0.3=py36_0
  - expat=2.2.6=he6710b0_0
  - fastcache=1.0.2=py36h14c3975_2
  - fftw3f=3.3.4=2
  - flask=1.0.2=py_2
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.9.1=h8a8886c_1
  - gast=0.2.2=py36_0
  - glib=2.56.2=hd408876_0
  - gmp=6.1.2=h6c8ec71_1
  - gmpy2=2.0.8=py36h10f8cd9_2
  - grpcio=1.16.1=py36hf8bcb03_1
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - h5py=2.9.0=py36h7918eee_0
  - hdf5=1.10.4=hb1b8bf9_0
  - heapdict=1.0.0=py36_2
  - icu=58.2=h9c2bf20_1
  - intel-openmp=2019.3=199
  - ipykernel=5.1.0=py36h39e3cac_0
  - ipyparallel=6.2.3=py36_0
  - ipython=7.4.0=py36h39e3cac_0
  - ipython_genutils=0.2.0=py36_0
  - ipywidgets=7.4.2=py36_0
  - itsdangerous=1.1.0=py_0
  - jedi=0.13.3=py36_0
  - jinja2=2.10=py_1
  - joblib=0.13.2=py36_0
  - jpeg=9b=h024ee3a_2
  - jsonschema=3.0.1=py36_0
  - jupyter=1.0.0=py36_7
  - jupyter_client=5.2.4=py36_0
  - jupyter_console=6.0.0=py36_0
  - jupyter_core=4.4.0=py36_0
  - keras=2.2.4=0
  - keras-applications=1.0.7=py_0
  - keras-base=2.2.4=py36_0
  - keras-preprocessing=1.0.9=py_0
  - kiwisolver=1.0.1=py36hf484d3e_0
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=8.2.0=hdf63c60_1
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.36=hbc83047_0
  - libprotobuf=3.6.1=hd408876_0
  - libsodium=1.0.16=h1bed415_0
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - libtiff=4.0.10=h2733197_2
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.9=he19cac6_0
  - llvmlite=0.28.0=py36hd408876_0
  - locket=0.2.0=py36_1
  - markdown=3.0.1=py36_0
  - markupsafe=1.1.1=py36h14c3975_0
  - matplotlib=3.0.3=py36h5429711_0
  - mistune=0.8.4=py36h7b6447c_0
  - mkl=2019.3=199
  - mkl_fft=1.0.10=py36ha843d7b_0
  - mkl_random=1.0.2=py36hd81dba3_0
  - mock=2.0.0=py36_0
  - more-itertools=6.0.0=py36_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.1=hdf1c602_3
  - mpmath=1.1.0=py36_0
  - msgpack-python=0.6.1=py36hfd86e86_1
  - multipledispatch=0.6.0=py_0
  - nbconvert=5.4.1=py36_3
  - nbformat=4.4.0=py36_0
  - ncurses=6.1=he6710b0_1
  - notebook=5.7.8=py36_0
  - numba=0.43.1=py36h962f231_0
  - numpy=1.16.2=py36h7e9f1db_0
  - numpy-base=1.16.2=py36hde5b4d6_0
  - olefile=0.46=py36_0
  - openssl=1.1.1b=h14c3975_1
  - packaging=19.0=py36_0
  - pandas=0.24.2=py36he6710b0_0
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py36_1
  - parso=0.3.4=py36_0
  - partd=0.3.10=py36_1
  - patsy=0.5.1=py36_0
  - pbr=5.1.3=py_0
  - pcre=8.43=he6710b0_0
  - pexpect=4.6.0=py36_0
  - periodictable
  - pickleshare=0.7.5=py36_0
  - pillow=5.4.1=py36h34e0f95_0
  - pip=19.0.3=py36_0
  - pluggy=0.9.0=py36_0
  - prometheus_client=0.6.0=py36_0
  - prompt_toolkit=2.0.9=py36_0
  - protobuf=3.6.1=py36he6710b0_0
  - psutil=5.6.1=py36h7b6447c_0
  - ptyprocess=0.6.0=py36_0
  - py=1.8.0=py36_0
  - pygments=2.3.1=py36_0
  - pyparsing=2.3.1=py36_0
  - pyqt=5.9.2=py36h05f1152_2
  - pyrsistent=0.14.11=py36h7b6447c_0
  - pytest=4.3.1=py36_0
  - pytest-cov
  - python=3.6.8=h0371630_0
  - python-dateutil=2.8.0=py36_0
  - pytz=2018.9=py36_0
  - pyyaml=5.1=py36h7b6447c_0
  - pyzmq=18.0.0=py36he6710b0_0
  - qt=5.9.7=h5867ecd_1
  - qtconsole=4.4.3=py36_0
  - readline=7.0=h7b6447c_5
  - scikit-learn=0.20.3=py36hd81dba3_0
  - scipy=1.2.1=py36h7c811a0_0
  - seaborn=0.9.0=py36_0
  - send2trash=1.5.0=py36_0
  - setuptools=40.8.0=py36_0
  - sip=4.19.8=py36hf484d3e_0
  - six=1.12.0=py36_0
  - sortedcontainers=2.1.0=py36_0
  - sqlite=3.27.2=h7b6447c_0
  - statsmodels=0.9.0=py36h035aef0_0
  - sympy=1.3=py36_0
  - tblib=1.3.2=py36_0
  - tensorboard=1.13.1=py36hf484d3e_0
  - tensorflow=1.13.1=mkl_py36h27d456a_0
  - tensorflow-base=1.13.1=mkl_py36h7ce6ba3_0
  - tensorflow-estimator=1.13.0=py_0
  - termcolor=1.1.0=py36_1
  - terminado=0.8.1=py36_1
  - testpath=0.4.2=py36_0
  - tk=8.6.8=hbc83047_0
  - toolz=0.9.0=py36_0
  - tornado=6.0.2=py36h7b6447c_0
  - traitlets=4.3.2=py36_0
  - wcwidth=0.1.7=py36_0
  - webencodings=0.5.1=py36_1
  - werkzeug=0.14.1=py36_0
  - wheel=0.33.1=py36_0
  - widgetsnbextension=3.4.2=py36_0
  - xz=5.2.4=h14c3975_4
  - yaml=0.1.7=had09818_2
  - zeromq=4.3.1=he6710b0_3
  - zict=0.1.4=py36_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
  - pip:
    - astroid==2.2.5
    - autopep8==1.4.3
    - cython==0.29.7
    - future==0.17.1
    - isort==4.3.16
    - lazy-object-proxy==1.3.1
    - mccabe==0.6.1
    - pycodestyle==2.5.0
    - pydocstyle==3.0.0
    - pyflakes==2.1.1
    - pylint==2.3.1
    - python-jsonrpc-server==0.1.2
    - python-language-server==0.26.1
    - rope==0.14.0
    - snowballstemmer==1.2.1
    - typed-ast==1.3.1
    - wrapt==1.11.1
    - yapf==0.26.0
    - codecov 

